const cabecalho = document.getElementById('cabecalho')
const menu = document.getElementById('menu')
const principal = document.getElementById('principal')
const btn_home = document.getElementById('btn_home')
const btn_novo = document.getElementById('btn_novo')
const btn_pesquisar = document.getElementById('btn_pesquisar')
const btn_gestao = document.getElementById('btn_gestao')
const btn_sobre = document.getElementById('btn_sobre')